from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol, runtime_checkable

from memory.ingestion.models import ChatEvidenceRecord, ToolCursor, ToolEvidenceRecord


@runtime_checkable
class TextIngestSink(Protocol):
    def notify_chat_messages(self, *, user_id: int, message_ids: Sequence[int]) -> bool: ...
    def notify_tool_inserted(self, *, user_id: int, ref: str) -> bool: ...
    def notify_tool_deleted(self, *, user_id: int, ref: str) -> bool: ...
    def wake_scanner(self) -> None: ...


@runtime_checkable
class ChatEvidenceReader(Protocol):
    def max_message_id(self) -> int: ...
    def read_messages_after_id(self, message_id: int, *, limit: int) -> Sequence[ChatEvidenceRecord]: ...
    def get_message_for_user(self, message_id: int, user_id: int) -> ChatEvidenceRecord | None: ...


@runtime_checkable
class ToolEvidenceReader(Protocol):
    def scan_head(self) -> ToolCursor: ...
    def read_after(self, cursor: ToolCursor, *, limit: int) -> Sequence[ToolEvidenceRecord]: ...
    def get_by_ref_for_user(self, ref: str, user_id: int) -> ToolEvidenceRecord | None: ...
    def existing_refs(self, items: Sequence[tuple[int, str]]) -> set[tuple[int, str]]: ...


@runtime_checkable
class ToolResultLifecycleObserver(Protocol):
    def inserted(self, *, user_id: int, ref: str) -> None: ...
    def deleted(self, *, user_id: int, ref: str, reason: str) -> None: ...
