"""Auto-generated Yandex Music tool registry — do not edit by hand."""

from __future__ import annotations

from typing import Any

MUSIC_TOOL_REGISTRY: tuple[dict[str, Any], ...] = (
    {
        "method": "account_experiments",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `account_experiments` (account experiments). Получение значений экспериментальных функций аккаунта.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "account_experiments_details",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `account_experiments_details` (account experiments details). Получение детальной информации об экспериментальных функциях аккаунта.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "account_settings",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `account_settings` (account settings). Получение настроек текущего пользователя.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "account_settings_set",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `account_settings_set` (account settings set). Изменение настроек текущего пользователя.',
        "schema": {'type': 'object', 'properties': {'param': {'description': 'Parameter `param` (passed to Yandex Music API).'}, 'value': {'description': 'Parameter `value` (passed to Yandex Music API).'}, 'data': {'type': 'array', 'items': {}}}, 'additionalProperties': True},
    },
    {
        "method": "account_status",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `account_status` (account status). Получение статуса аккаунта. Нет обязательных параметров.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "after_track",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `after_track` (after track). Получение рекламы или шота от Алисы после трека.',
        "schema": {'type': 'object', 'properties': {'next_track_id': {'type': 'string'}, 'context_item': {'description': 'Parameter `context_item` (passed to Yandex Music API).'}, 'prev_track_id': {'type': 'string'}, 'context': {'type': 'string', 'default': 'playlist'}, 'types': {'type': 'string', 'default': 'shot'}, 'from': {'type': 'string', 'default': 'mobile-landing-origin-default', 'description': 'Alias for API parameter `from`.'}}, 'required': ['next_track_id', 'context_item'], 'additionalProperties': True},
    },
    {
        "method": "albums",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `albums` (albums). Получение альбома/альбомов.',
        "schema": {'type': 'object', 'properties': {'album_ids': {'type': 'string'}}, 'required': ['album_ids'], 'additionalProperties': True},
    },
    {
        "method": "albums_disclaimer",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `albums_disclaimer` (albums disclaimer). Получение дисклеймера альбома.',
        "schema": {'type': 'object', 'properties': {'album_id': {'type': 'string'}}, 'required': ['album_id'], 'additionalProperties': True},
    },
    {
        "method": "albums_similar_entities",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `albums_similar_entities` (albums similar entities). Получение похожих сущностей для альбома.',
        "schema": {'type': 'object', 'properties': {'album_id': {'type': 'string'}}, 'required': ['album_id'], 'additionalProperties': True},
    },
    {
        "method": "albums_trailer",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `albums_trailer` (albums trailer). Получение трейлера альбома.',
        "schema": {'type': 'object', 'properties': {'album_id': {'type': 'string'}}, 'required': ['album_id'], 'additionalProperties': True},
    },
    {
        "method": "albums_with_tracks",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `albums_with_tracks` (albums with tracks). Получение альбома по его уникальному идентификатору вместе с треками.',
        "schema": {'type': 'object', 'properties': {'album_id': {'type': 'string'}}, 'required': ['album_id'], 'additionalProperties': True},
    },
    {
        "method": "artists",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists` (artists). Получение исполнителя/исполнителей.',
        "schema": {'type': 'object', 'properties': {'artist_ids': {'type': 'string'}}, 'required': ['artist_ids'], 'additionalProperties': True},
    },
    {
        "method": "artists_about",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_about` (artists about). Получение информации «Об артисте».',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_also_albums",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_also_albums` (artists also albums). Получение сборников и альбомов, в которых участвовал артист.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}, 'page': {'type': 'integer', 'default': 0}, 'page_size': {'type': 'integer', 'default': 20}, 'sort_by': {'type': 'string', 'default': 'year'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_brief_info",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_brief_info` (artists brief info). Получение информации об артисте.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_clips",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_clips` (artists clips). Получение клипов артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_concerts",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_concerts` (artists concerts). Получение концертов артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_direct_albums",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_direct_albums` (artists direct albums). Получение альбомов артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}, 'page': {'type': 'integer', 'default': 0}, 'page_size': {'type': 'integer', 'default': 20}, 'sort_by': {'type': 'string', 'default': 'year'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_disclaimer",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_disclaimer` (artists disclaimer). Получение дисклеймера артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_discography_albums",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_discography_albums` (artists discography albums). Получение дискографии артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}, 'page': {'type': 'integer', 'default': 0}, 'page_size': {'type': 'integer', 'default': 20}, 'sort_by': {'type': 'string', 'default': 'year'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_donation",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_donation` (artists donation). Получение информации о донатах артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_info",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_info` (artists info). Получение подробной информации об артисте.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_links",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_links` (artists links). Получение ссылок на страницы артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_safe_direct_albums",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_safe_direct_albums` (artists safe direct albums). Получение безопасных альбомов артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}, 'sort_by': {'type': 'string', 'default': 'year'}, 'sort_order': {'type': 'string', 'default': 'desc'}, 'limit': {'type': 'integer', 'default': 20}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_similar",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_similar` (artists similar). Получение похожих артистов.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_skeleton",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_skeleton` (artists skeleton). Получение скелетона страницы артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}, 'skeleton_id': {'type': 'string', 'default': 'web-artist-default'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_track_ids",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_track_ids` (artists track ids). Получение идентификаторов треков артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}, 'page': {'type': 'integer', 'default': 0}, 'page_size': {'type': 'integer', 'default': 20}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_tracks",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_tracks` (artists tracks). Получение треков артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}, 'page': {'type': 'integer', 'default': 0}, 'page_size': {'type': 'integer', 'default': 20}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "artists_trailer",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `artists_trailer` (artists trailer). Получение трейлера артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "chart",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `chart` (chart). Получение чарта.',
        "schema": {'type': 'object', 'properties': {'chart_option': {'type': 'string', 'default': ''}}, 'additionalProperties': True},
    },
    {
        "method": "clips",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `clips` (clips). Получение клипов по идентификаторам.',
        "schema": {'type': 'object', 'properties': {'clip_ids': {'type': 'string'}}, 'required': ['clip_ids'], 'additionalProperties': True},
    },
    {
        "method": "clips_credits",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `clips_credits` (clips credits). Получение информации об участниках создания клипа.',
        "schema": {'type': 'object', 'properties': {'clip_id': {'type': 'string'}}, 'required': ['clip_id'], 'additionalProperties': True},
    },
    {
        "method": "clips_disclaimer",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `clips_disclaimer` (clips disclaimer). Получение дисклеймера клипа.',
        "schema": {'type': 'object', 'properties': {'clip_id': {'type': 'string'}}, 'required': ['clip_id'], 'additionalProperties': True},
    },
    {
        "method": "clips_will_like",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `clips_will_like` (clips will like). Получение подборки рекомендуемых клипов.',
        "schema": {'type': 'object', 'properties': {'page': {'type': 'integer', 'default': 0}, 'page_size': {'type': 'integer', 'default': 50}}, 'additionalProperties': True},
    },
    {
        "method": "concert_info",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `concert_info` (concert info). Получение информации о концерте.',
        "schema": {'type': 'object', 'properties': {'concert_id': {'type': 'string'}}, 'required': ['concert_id'], 'additionalProperties': True},
    },
    {
        "method": "concert_skeleton",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `concert_skeleton` (concert skeleton). Получение скелетона страницы концерта.',
        "schema": {'type': 'object', 'properties': {'concert_id': {'type': 'string'}, 'skeleton_id': {'type': 'string', 'default': 'concert_page'}}, 'required': ['concert_id'], 'additionalProperties': True},
    },
    {
        "method": "concerts_feed",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `concerts_feed` (concerts feed). Получение ленты концертов.',
        "schema": {'type': 'object', 'properties': {'locations': {'description': 'Parameter `locations` (passed to Yandex Music API).'}}, 'additionalProperties': True},
    },
    {
        "method": "concerts_locations",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `concerts_locations` (concerts locations). Получение списка местоположений для фильтрации концертов.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "concerts_tab_config",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `concerts_tab_config` (concerts tab config). Получение конфигурации вкладок концертов.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "consume_promo_code",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `consume_promo_code` (consume promo code). Активация промо-кода.',
        "schema": {'type': 'object', 'properties': {'code': {'description': 'Parameter `code` (passed to Yandex Music API).'}, 'language': {'description': 'Parameter `language` (passed to Yandex Music API).'}}, 'required': ['code'], 'additionalProperties': True},
    },
    {
        "method": "feed",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `feed` (feed). Получение потока информации (фида) подобранного под пользователя. Содержит умные плейлисты.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "feed_wizard_is_passed",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `feed_wizard_is_passed` (feed wizard is passed). Получение информации о прохождении визарда.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "genres",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `genres` (genres). Получение жанров музыки.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "init",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `init` (init). Получение информации об аккаунте, использующейся в других запросах.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "label",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `label` (label). Получение информации о лейбле.',
        "schema": {'type': 'object', 'properties': {'label_id': {'type': 'string'}}, 'required': ['label_id'], 'additionalProperties': True},
    },
    {
        "method": "label_albums",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `label_albums` (label albums). Получение альбомов лейбла.',
        "schema": {'type': 'object', 'properties': {'label_id': {'type': 'string'}, 'page': {'type': 'integer', 'default': 0}, 'page_size': {'type': 'integer', 'default': 100}, 'sort_by': {'description': 'Parameter `sort_by` (passed to Yandex Music API).'}, 'sort_order': {'description': 'Parameter `sort_order` (passed to Yandex Music API).'}}, 'required': ['label_id'], 'additionalProperties': True},
    },
    {
        "method": "label_artists",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `label_artists` (label artists). Получение артистов лейбла.',
        "schema": {'type': 'object', 'properties': {'label_id': {'type': 'string'}, 'page': {'type': 'integer', 'default': 0}, 'page_size': {'type': 'integer', 'default': 100}}, 'required': ['label_id'], 'additionalProperties': True},
    },
    {
        "method": "landing",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `landing` (landing). Получение лендинг-страницы содержащий блоки с новыми релизами, чартами, плейлистами с новинками и т.д.',
        "schema": {'type': 'object', 'properties': {'blocks': {'description': 'Parameter `blocks` (passed to Yandex Music API).'}}, 'required': ['blocks'], 'additionalProperties': True},
    },
    {
        "method": "metatag",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `metatag` (metatag). Получение информации о метатеге.',
        "schema": {'type': 'object', 'properties': {'metatag_id': {'type': 'string'}, 'tracks_count': {'description': 'Parameter `tracks_count` (passed to Yandex Music API).'}, 'artists_count': {'description': 'Parameter `artists_count` (passed to Yandex Music API).'}, 'composers_count': {'description': 'Parameter `composers_count` (passed to Yandex Music API).'}, 'albums_count': {'description': 'Parameter `albums_count` (passed to Yandex Music API).'}, 'promotions_count': {'description': 'Parameter `promotions_count` (passed to Yandex Music API).'}, 'features_count': {'description': 'Parameter `features_count` (passed to Yandex Music API).'}, 'playlists_count': {'description': 'Parameter `playlists_count` (passed to Yandex Music API).'}, 'concerts_count': {'description': 'Parameter `concerts_count` (passed to Yandex Music API).'}, 'tracks_sort_by': {'description': 'Parameter `tracks_sort_by` (passed to Yandex Music API).'}, 'albums_sort_by': {'description': 'Parameter `albums_sort_by` (passed to Yandex Music API).'}, 'with_likes_count': {'description': 'Parameter `with_likes_count` (passed to Yandex Music API).'}}, 'required': ['metatag_id'], 'additionalProperties': True},
    },
    {
        "method": "metatag_albums",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `metatag_albums` (metatag albums). Получение альбомов метатега.',
        "schema": {'type': 'object', 'properties': {'metatag_id': {'type': 'string'}, 'period': {'description': 'Parameter `period` (passed to Yandex Music API).'}, 'sort_by': {'description': 'Parameter `sort_by` (passed to Yandex Music API).'}, 'offset': {'type': 'integer', 'default': 0}, 'limit': {'type': 'integer', 'default': 25}}, 'required': ['metatag_id'], 'additionalProperties': True},
    },
    {
        "method": "metatag_artists",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `metatag_artists` (metatag artists). Получение артистов метатега.',
        "schema": {'type': 'object', 'properties': {'metatag_id': {'type': 'string'}, 'period': {'type': 'string', 'default': 'week'}, 'sort_by': {'description': 'Parameter `sort_by` (passed to Yandex Music API).'}, 'offset': {'type': 'integer', 'default': 0}, 'limit': {'type': 'integer', 'default': 25}, 'tracks_per_artist': {'description': 'Parameter `tracks_per_artist` (passed to Yandex Music API).'}}, 'required': ['metatag_id'], 'additionalProperties': True},
    },
    {
        "method": "metatag_playlists",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `metatag_playlists` (metatag playlists). Получение плейлистов метатега.',
        "schema": {'type': 'object', 'properties': {'metatag_id': {'type': 'string'}, 'sort_by': {'description': 'Parameter `sort_by` (passed to Yandex Music API).'}, 'offset': {'type': 'integer', 'default': 0}, 'limit': {'type': 'integer', 'default': 25}, 'with_likes_count': {'description': 'Parameter `with_likes_count` (passed to Yandex Music API).'}}, 'required': ['metatag_id'], 'additionalProperties': True},
    },
    {
        "method": "metatags",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `metatags` (metatags). Получение дерева метатегов.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "music_history",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `music_history` (music history). Получение истории прослушивания.',
        "schema": {'type': 'object', 'properties': {'full_models_count': {'type': 'integer', 'default': 0}}, 'additionalProperties': True},
    },
    {
        "method": "music_history_items",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `music_history_items` (music history items). Получение элементов истории прослушивания по списку идентификаторов.',
        "schema": {'type': 'object', 'properties': {'track_ids': {'type': 'string'}, 'album_ids': {'type': 'string'}, 'artist_ids': {'type': 'string'}, 'playlist_ids': {'type': 'string'}, 'wave_seeds': {'description': 'Parameter `wave_seeds` (passed to Yandex Music API).'}}, 'additionalProperties': True},
    },
    {
        "method": "new_playlists",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `new_playlists` (new playlists). Получение полного списка всех новых плейлистов.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "new_releases",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `new_releases` (new releases). Получение полного списка всех новых релизов (альбомов).',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "permission_alerts",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `permission_alerts` (permission alerts). Получение оповещений. Нет обязательных параметров.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "pin_album",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `pin_album` (pin album). Закрепление альбома.',
        "schema": {'type': 'object', 'properties': {'album_id': {'type': 'string'}}, 'required': ['album_id'], 'additionalProperties': True},
    },
    {
        "method": "pin_artist",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `pin_artist` (pin artist). Закрепление артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "pin_playlist",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `pin_playlist` (pin playlist). Закрепление плейлиста.',
        "schema": {'type': 'object', 'properties': {'uid': {'description': 'Parameter `uid` (passed to Yandex Music API).'}, 'kind': {'description': 'Parameter `kind` (passed to Yandex Music API).'}}, 'required': ['uid', 'kind'], 'additionalProperties': True},
    },
    {
        "method": "pin_wave",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `pin_wave` (pin wave). Закрепление волны.',
        "schema": {'type': 'object', 'properties': {'seeds': {'description': 'Parameter `seeds` (passed to Yandex Music API).'}}, 'required': ['seeds'], 'additionalProperties': True},
    },
    {
        "method": "pins",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `pins` (pins). Получение списка закреплённых элементов.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "play_audio",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `play_audio` (play audio). Метод для отправки текущего состояния прослушиваемого трека.',
        "schema": {'type': 'object', 'properties': {'track_id': {'type': 'string'}, 'from': {'description': 'Alias for API parameter `from`.'}, 'album_id': {'type': 'string'}, 'playlist_id': {'type': 'string'}, 'from_cache': {'type': 'boolean', 'default': False}, 'play_id': {'type': 'string'}, 'uid': {'description': 'Parameter `uid` (passed to Yandex Music API).'}, 'timestamp': {'type': 'integer'}, 'track_length_seconds': {'type': 'integer', 'default': 0}, 'total_played_seconds': {'type': 'integer', 'default': 0}, 'end_position_seconds': {'type': 'integer', 'default': 0}, 'client_now': {'description': 'Parameter `client_now` (passed to Yandex Music API).'}}, 'required': ['track_id', 'album_id'], 'additionalProperties': True},
    },
    {
        "method": "playlist",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `playlist` (playlist). Получение плейлиста по его UUID.',
        "schema": {'type': 'object', 'properties': {'playlist_uuid': {'description': 'Parameter `playlist_uuid` (passed to Yandex Music API).'}}, 'required': ['playlist_uuid'], 'additionalProperties': True},
    },
    {
        "method": "playlist_similar_entities",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `playlist_similar_entities` (playlist similar entities). Получение похожих сущностей для плейлиста.',
        "schema": {'type': 'object', 'properties': {'playlist_uuid': {'description': 'Parameter `playlist_uuid` (passed to Yandex Music API).'}}, 'required': ['playlist_uuid'], 'additionalProperties': True},
    },
    {
        "method": "playlists",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `playlists` (playlists). Получение списка плейлистов по идентификаторам.',
        "schema": {'type': 'object', 'properties': {'playlist_ids': {'type': 'string'}}, 'required': ['playlist_ids'], 'additionalProperties': True},
    },
    {
        "method": "playlists_collective_join",
        "auth": False,
        "write": True,
        "description": 'Yandex Music API `playlists_collective_join` (playlists collective join). Присоединение к плейлисту как соавтор.',
        "schema": {'type': 'object', 'properties': {'user_id': {'type': 'string'}, 'token': {'description': 'Parameter `token` (passed to Yandex Music API).'}}, 'required': ['user_id', 'token'], 'additionalProperties': True},
    },
    {
        "method": "playlists_list",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `playlists_list` (playlists list). Получение плейлиста/плейлистов.',
        "schema": {'type': 'object', 'properties': {'playlist_ids': {'type': 'string'}}, 'required': ['playlist_ids'], 'additionalProperties': True},
    },
    {
        "method": "playlists_personal",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `playlists_personal` (playlists personal). Получение персонального плейлиста.',
        "schema": {'type': 'object', 'properties': {'playlist_id': {'type': 'string'}}, 'required': ['playlist_id'], 'additionalProperties': True},
    },
    {
        "method": "podcasts",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `podcasts` (podcasts). Получение подкастов с лендинга.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "queue",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `queue` (queue). Получение информации об очереди треков и самих треков в ней.',
        "schema": {'type': 'object', 'properties': {'queue_id': {'type': 'string'}}, 'required': ['queue_id'], 'additionalProperties': True},
    },
    {
        "method": "queue_create",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `queue_create` (queue create). Создание новой очереди треков.',
        "schema": {'type': 'object', 'properties': {'queue': {'description': 'Parameter `queue` (passed to Yandex Music API).'}, 'device': {'description': 'Parameter `device` (passed to Yandex Music API).'}}, 'required': ['queue'], 'additionalProperties': True},
    },
    {
        "method": "queue_update_position",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `queue_update_position` (queue update position). Установка текущего индекса проигрываемого трека в очереди треков.',
        "schema": {'type': 'object', 'properties': {'queue_id': {'type': 'string'}, 'current_index': {'description': 'Parameter `current_index` (passed to Yandex Music API).'}, 'device': {'description': 'Parameter `device` (passed to Yandex Music API).'}}, 'required': ['queue_id', 'current_index'], 'additionalProperties': True},
    },
    {
        "method": "queues_list",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `queues_list` (queues list). Получение всех очередей треков с разных устройств для синхронизации между ними.',
        "schema": {'type': 'object', 'properties': {'device': {'description': 'Parameter `device` (passed to Yandex Music API).'}}, 'additionalProperties': True},
    },
    {
        "method": "rotor_account_status",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `rotor_account_status` (rotor account status). Получение статуса пользователя с дополнительными полями.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "rotor_station_feedback",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `rotor_station_feedback` (rotor station feedback). Отправка обратной связи на действия при прослушивании радио.',
        "schema": {'type': 'object', 'properties': {'station': {'description': 'Parameter `station` (passed to Yandex Music API).'}, 'type_': {'type': 'string'}, 'timestamp': {'type': 'integer'}, 'from': {'description': 'Alias for API parameter `from`.'}, 'batch_id': {'type': 'string'}, 'total_played_seconds': {'description': 'Parameter `total_played_seconds` (passed to Yandex Music API).'}, 'track_id': {'type': 'string'}}, 'required': ['station', 'type_'], 'additionalProperties': True},
    },
    {
        "method": "rotor_station_feedback_radio_started",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `rotor_station_feedback_radio_started` (rotor station feedback radio started). Отправить обратную связь: радио запущено.',
        "schema": {'type': 'object', 'properties': {'station': {'description': 'Parameter `station` (passed to Yandex Music API).'}, 'from': {'description': 'Alias for API parameter `from`.'}, 'batch_id': {'type': 'string'}, 'timestamp': {'type': 'integer'}}, 'required': ['station'], 'additionalProperties': True},
    },
    {
        "method": "rotor_station_feedback_skip",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `rotor_station_feedback_skip` (rotor station feedback skip). Отправить обратную связь: трек пропущен.',
        "schema": {'type': 'object', 'properties': {'station': {'description': 'Parameter `station` (passed to Yandex Music API).'}, 'track_id': {'type': 'string'}, 'total_played_seconds': {'description': 'Parameter `total_played_seconds` (passed to Yandex Music API).'}, 'batch_id': {'type': 'string'}, 'timestamp': {'type': 'integer'}}, 'required': ['station', 'track_id', 'total_played_seconds'], 'additionalProperties': True},
    },
    {
        "method": "rotor_station_feedback_track_finished",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `rotor_station_feedback_track_finished` (rotor station feedback track finished). Отправить обратную связь: трек дослушан.',
        "schema": {'type': 'object', 'properties': {'station': {'description': 'Parameter `station` (passed to Yandex Music API).'}, 'track_id': {'type': 'string'}, 'total_played_seconds': {'description': 'Parameter `total_played_seconds` (passed to Yandex Music API).'}, 'batch_id': {'type': 'string'}, 'timestamp': {'type': 'integer'}}, 'required': ['station', 'track_id', 'total_played_seconds'], 'additionalProperties': True},
    },
    {
        "method": "rotor_station_feedback_track_started",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `rotor_station_feedback_track_started` (rotor station feedback track started). Отправить обратную связь: трек запущен.',
        "schema": {'type': 'object', 'properties': {'station': {'description': 'Parameter `station` (passed to Yandex Music API).'}, 'track_id': {'type': 'string'}, 'batch_id': {'type': 'string'}, 'timestamp': {'type': 'integer'}}, 'required': ['station', 'track_id'], 'additionalProperties': True},
    },
    {
        "method": "rotor_station_info",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `rotor_station_info` (rotor station info). Получение информации о станции и пользовательских настроек на неё.',
        "schema": {'type': 'object', 'properties': {'station': {'description': 'Parameter `station` (passed to Yandex Music API).'}}, 'required': ['station'], 'additionalProperties': True},
    },
    {
        "method": "rotor_station_settings2",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `rotor_station_settings2` (rotor station settings2). Изменение настроек определённой станции.',
        "schema": {'type': 'object', 'properties': {'station': {'description': 'Parameter `station` (passed to Yandex Music API).'}, 'mood_energy': {'description': 'Parameter `mood_energy` (passed to Yandex Music API).'}, 'diversity': {'description': 'Parameter `diversity` (passed to Yandex Music API).'}, 'language': {'type': 'string', 'default': 'not-russian'}, 'type_': {'type': 'string', 'default': 'rotor'}}, 'required': ['station', 'mood_energy', 'diversity'], 'additionalProperties': True},
    },
    {
        "method": "rotor_station_tracks",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `rotor_station_tracks` (rotor station tracks). Получение цепочки треков определённой станции.',
        "schema": {'type': 'object', 'properties': {'station': {'description': 'Parameter `station` (passed to Yandex Music API).'}, 'settings2': {'type': 'boolean', 'default': True}, 'queue': {'description': 'Parameter `queue` (passed to Yandex Music API).'}}, 'required': ['station'], 'additionalProperties': True},
    },
    {
        "method": "rotor_stations_dashboard",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `rotor_stations_dashboard` (rotor stations dashboard). Получение рекомендованных станций текущего пользователя.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "rotor_stations_list",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `rotor_stations_list` (rotor stations list). Получение всех радиостанций с настройками пользователя.',
        "schema": {'type': 'object', 'properties': {'language': {'description': 'Parameter `language` (passed to Yandex Music API).'}}, 'additionalProperties': True},
    },
    {
        "method": "search",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `search` (search). Осуществление поиска по запросу и типу, получение результатов.',
        "schema": {'type': 'object', 'properties': {'text': {'type': 'string'}, 'nocorrect': {'type': 'boolean', 'default': False}, 'type_': {'type': 'string', 'default': 'all'}, 'page': {'type': 'integer', 'default': 0}, 'playlist_in_best': {'type': 'boolean', 'default': True}}, 'required': ['text'], 'additionalProperties': True},
    },
    {
        "method": "search_suggest",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `search_suggest` (search suggest). Получение подсказок по введенной части поискового запроса.',
        "schema": {'type': 'object', 'properties': {'part': {'type': 'string'}}, 'required': ['part'], 'additionalProperties': True},
    },
    {
        "method": "settings",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `settings` (settings). Получение предложений по покупке. Нет обязательных параметров.',
        "schema": {'type': 'object', 'properties': {}, 'additionalProperties': True},
    },
    {
        "method": "tags",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `tags` (tags). Получение тега (подборки).',
        "schema": {'type': 'object', 'properties': {'tag_id': {'type': 'string'}}, 'required': ['tag_id'], 'additionalProperties': True},
    },
    {
        "method": "track_supplement",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `track_supplement` (track supplement). Получение дополнительной информации о треке.',
        "schema": {'type': 'object', 'properties': {'track_id': {'type': 'string'}}, 'required': ['track_id'], 'additionalProperties': True},
    },
    {
        "method": "tracks",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `tracks` (tracks). Получение трека/треков.',
        "schema": {'type': 'object', 'properties': {'track_ids': {'type': 'string'}, 'with_positions': {'type': 'boolean', 'default': True}}, 'required': ['track_ids'], 'additionalProperties': True},
    },
    {
        "method": "tracks_credits",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `tracks_credits` (tracks credits). Получение информации об участниках создания трека.',
        "schema": {'type': 'object', 'properties': {'track_id': {'type': 'string'}}, 'required': ['track_id'], 'additionalProperties': True},
    },
    {
        "method": "tracks_disclaimer",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `tracks_disclaimer` (tracks disclaimer). Получение дисклеймера трека.',
        "schema": {'type': 'object', 'properties': {'track_id': {'type': 'string'}}, 'required': ['track_id'], 'additionalProperties': True},
    },
    {
        "method": "tracks_download_info",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `tracks_download_info` (tracks download info). Получение информации о доступных вариантах загрузки трека.',
        "schema": {'type': 'object', 'properties': {'track_id': {'type': 'string'}, 'get_direct_links': {'type': 'boolean', 'default': False}}, 'required': ['track_id'], 'additionalProperties': True},
    },
    {
        "method": "tracks_full_info",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `tracks_full_info` (tracks full info). Получение полной информации о треке.',
        "schema": {'type': 'object', 'properties': {'track_id': {'type': 'string'}}, 'required': ['track_id'], 'additionalProperties': True},
    },
    {
        "method": "tracks_lyrics",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `tracks_lyrics` (tracks lyrics). Получение текста трека.',
        "schema": {'type': 'object', 'properties': {'track_id': {'type': 'string'}, 'format_': {'type': 'string', 'default': 'TEXT'}}, 'required': ['track_id'], 'additionalProperties': True},
    },
    {
        "method": "tracks_similar",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `tracks_similar` (tracks similar). Получение похожих треков.',
        "schema": {'type': 'object', 'properties': {'track_id': {'type': 'string'}}, 'required': ['track_id'], 'additionalProperties': True},
    },
    {
        "method": "tracks_trailer",
        "auth": False,
        "write": False,
        "description": 'Yandex Music API `tracks_trailer` (tracks trailer). Получение трейлера трека.',
        "schema": {'type': 'object', 'properties': {'track_id': {'type': 'string'}}, 'required': ['track_id'], 'additionalProperties': True},
    },
    {
        "method": "unpin_album",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `unpin_album` (unpin album). Открепление альбома.',
        "schema": {'type': 'object', 'properties': {'album_id': {'type': 'string'}}, 'required': ['album_id'], 'additionalProperties': True},
    },
    {
        "method": "unpin_artist",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `unpin_artist` (unpin artist). Открепление артиста.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "unpin_playlist",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `unpin_playlist` (unpin playlist). Открепление плейлиста.',
        "schema": {'type': 'object', 'properties': {'uid': {'description': 'Parameter `uid` (passed to Yandex Music API).'}, 'kind': {'description': 'Parameter `kind` (passed to Yandex Music API).'}}, 'required': ['uid', 'kind'], 'additionalProperties': True},
    },
    {
        "method": "unpin_wave",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `unpin_wave` (unpin wave). Открепление волны.',
        "schema": {'type': 'object', 'properties': {'seeds': {'description': 'Parameter `seeds` (passed to Yandex Music API).'}}, 'required': ['seeds'], 'additionalProperties': True},
    },
    {
        "method": "users_dislikes_artists",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_dislikes_artists` (users dislikes artists). Получение исполнителей с отметкой "Не рекомендовать".',
        "schema": {'type': 'object', 'properties': {'user_id': {'type': 'string'}}, 'additionalProperties': True},
    },
    {
        "method": "users_dislikes_artists_add",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_dislikes_artists_add` (users dislikes artists add). Поставить отметку "Не рекомендовать" исполнителю.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "users_dislikes_artists_remove",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_dislikes_artists_remove` (users dislikes artists remove). Снять отметку "Не рекомендовать" у исполнителя.',
        "schema": {'type': 'object', 'properties': {'artist_id': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['artist_id'], 'additionalProperties': True},
    },
    {
        "method": "users_dislikes_tracks",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_dislikes_tracks` (users dislikes tracks). Получение треков с отметкой "Не рекомендовать".',
        "schema": {'type': 'object', 'properties': {'user_id': {'type': 'string'}, 'if_modified_since_revision': {'type': 'integer', 'default': 0}}, 'additionalProperties': True},
    },
    {
        "method": "users_dislikes_tracks_add",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_dislikes_tracks_add` (users dislikes tracks add). Поставить отметку "Не рекомендовать" треку/трекам.',
        "schema": {'type': 'object', 'properties': {'track_ids': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['track_ids'], 'additionalProperties': True},
    },
    {
        "method": "users_dislikes_tracks_remove",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_dislikes_tracks_remove` (users dislikes tracks remove). Снять отметку "Не рекомендовать" у трека/треков.',
        "schema": {'type': 'object', 'properties': {'track_ids': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['track_ids'], 'additionalProperties': True},
    },
    {
        "method": "users_likes_albums",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_likes_albums` (users likes albums). Получение альбомов с отметкой "Мне нравится".',
        "schema": {'type': 'object', 'properties': {'user_id': {'type': 'string'}, 'rich': {'type': 'boolean', 'default': True}}, 'additionalProperties': True},
    },
    {
        "method": "users_likes_albums_add",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_likes_albums_add` (users likes albums add). Поставить отметку "Мне нравится" альбому/альбомам.',
        "schema": {'type': 'object', 'properties': {'album_ids': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['album_ids'], 'additionalProperties': True},
    },
    {
        "method": "users_likes_albums_remove",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_likes_albums_remove` (users likes albums remove). Снять отметку "Мне нравится" у альбома/альбомов.',
        "schema": {'type': 'object', 'properties': {'album_ids': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['album_ids'], 'additionalProperties': True},
    },
    {
        "method": "users_likes_artists",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_likes_artists` (users likes artists). Получение артистов с отметкой "Мне нравится".',
        "schema": {'type': 'object', 'properties': {'user_id': {'type': 'string'}, 'with_timestamps': {'type': 'boolean', 'default': True}}, 'additionalProperties': True},
    },
    {
        "method": "users_likes_artists_add",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_likes_artists_add` (users likes artists add). Поставить отметку "Мне нравится" исполнителю/исполнителям.',
        "schema": {'type': 'object', 'properties': {'artist_ids': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['artist_ids'], 'additionalProperties': True},
    },
    {
        "method": "users_likes_artists_remove",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_likes_artists_remove` (users likes artists remove). Снять отметку "Мне нравится" у исполнителя/исполнителей.',
        "schema": {'type': 'object', 'properties': {'artist_ids': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['artist_ids'], 'additionalProperties': True},
    },
    {
        "method": "users_likes_clips",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_likes_clips` (users likes clips). Получение клипов с отметкой "Мне нравится".',
        "schema": {'type': 'object', 'properties': {'user_id': {'type': 'string'}, 'page': {'type': 'integer', 'default': 0}, 'page_size': {'type': 'integer', 'default': 100}}, 'additionalProperties': True},
    },
    {
        "method": "users_likes_clips_add",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_likes_clips_add` (users likes clips add). Поставить отметку "Мне нравится" клипу.',
        "schema": {'type': 'object', 'properties': {'clip_id': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['clip_id'], 'additionalProperties': True},
    },
    {
        "method": "users_likes_clips_remove",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_likes_clips_remove` (users likes clips remove). Снять отметку "Мне нравится" у клипа.',
        "schema": {'type': 'object', 'properties': {'clip_id': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['clip_id'], 'additionalProperties': True},
    },
    {
        "method": "users_likes_playlists",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_likes_playlists` (users likes playlists). Получение плейлистов с отметкой "Мне нравится".',
        "schema": {'type': 'object', 'properties': {'user_id': {'type': 'string'}}, 'additionalProperties': True},
    },
    {
        "method": "users_likes_playlists_add",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_likes_playlists_add` (users likes playlists add). Поставить отметку "Мне нравится" плейлисту/плейлистам.',
        "schema": {'type': 'object', 'properties': {'playlist_ids': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['playlist_ids'], 'additionalProperties': True},
    },
    {
        "method": "users_likes_playlists_remove",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_likes_playlists_remove` (users likes playlists remove). Снять отметку "Мне нравится" у плейлиста/плейлистов.',
        "schema": {'type': 'object', 'properties': {'playlist_ids': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['playlist_ids'], 'additionalProperties': True},
    },
    {
        "method": "users_likes_tracks",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_likes_tracks` (users likes tracks). Получение треков с отметкой "Мне нравится".',
        "schema": {'type': 'object', 'properties': {'user_id': {'type': 'string'}, 'if_modified_since_revision': {'type': 'integer', 'default': 0}}, 'additionalProperties': True},
    },
    {
        "method": "users_likes_tracks_add",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_likes_tracks_add` (users likes tracks add). Поставить отметку "Мне нравится" треку/трекам.',
        "schema": {'type': 'object', 'properties': {'track_ids': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['track_ids'], 'additionalProperties': True},
    },
    {
        "method": "users_likes_tracks_remove",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_likes_tracks_remove` (users likes tracks remove). Снять отметку "Мне нравится" у трека/треков.',
        "schema": {'type': 'object', 'properties': {'track_ids': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['track_ids'], 'additionalProperties': True},
    },
    {
        "method": "users_playlists",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_playlists` (users playlists). Получение плейлиста или списка плейлистов по уникальным идентификаторам.',
        "schema": {'type': 'object', 'properties': {'kind': {'description': 'Parameter `kind` (passed to Yandex Music API).'}, 'user_id': {'type': 'string'}}, 'required': ['kind'], 'additionalProperties': True},
    },
    {
        "method": "users_playlists_change",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_playlists_change` (users playlists change). Изменение плейлиста.',
        "schema": {'type': 'object', 'properties': {'kind': {'description': 'Parameter `kind` (passed to Yandex Music API).'}, 'diff': {'description': 'Parameter `diff` (passed to Yandex Music API).'}, 'revision': {'type': 'integer', 'default': 1}, 'user_id': {'type': 'string'}}, 'required': ['kind', 'diff'], 'additionalProperties': True},
    },
    {
        "method": "users_playlists_create",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_playlists_create` (users playlists create). Создание плейлиста.',
        "schema": {'type': 'object', 'properties': {'title': {'description': 'Parameter `title` (passed to Yandex Music API).'}, 'visibility': {'type': 'string', 'default': 'public'}, 'user_id': {'type': 'string'}}, 'required': ['title'], 'additionalProperties': True},
    },
    {
        "method": "users_playlists_delete",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_playlists_delete` (users playlists delete). Удаление плейлиста.',
        "schema": {'type': 'object', 'properties': {'kind': {'description': 'Parameter `kind` (passed to Yandex Music API).'}, 'user_id': {'type': 'string'}}, 'required': ['kind'], 'additionalProperties': True},
    },
    {
        "method": "users_playlists_delete_track",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_playlists_delete_track` (users playlists delete track). Удаление треков из плейлиста.',
        "schema": {'type': 'object', 'properties': {'kind': {'description': 'Parameter `kind` (passed to Yandex Music API).'}, 'from': {'description': 'Alias for API parameter `from`.'}, 'to': {'description': 'Parameter `to` (passed to Yandex Music API).'}, 'revision': {'type': 'integer', 'default': 1}, 'user_id': {'type': 'string'}}, 'required': ['kind', 'to'], 'additionalProperties': True},
    },
    {
        "method": "users_playlists_description",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_playlists_description` (users playlists description). Изменение описания плейлиста.',
        "schema": {'type': 'object', 'properties': {'kind': {'description': 'Parameter `kind` (passed to Yandex Music API).'}, 'description': {'description': 'Parameter `description` (passed to Yandex Music API).'}, 'user_id': {'type': 'string'}}, 'required': ['kind', 'description'], 'additionalProperties': True},
    },
    {
        "method": "users_playlists_insert_track",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_playlists_insert_track` (users playlists insert track). Добавление трека в плейлист.',
        "schema": {'type': 'object', 'properties': {'kind': {'description': 'Parameter `kind` (passed to Yandex Music API).'}, 'track_id': {'type': 'string'}, 'album_id': {'type': 'string'}, 'at': {'type': 'integer', 'default': 0}, 'revision': {'type': 'integer', 'default': 1}, 'user_id': {'type': 'string'}}, 'required': ['kind', 'track_id', 'album_id'], 'additionalProperties': True},
    },
    {
        "method": "users_playlists_kinds",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_playlists_kinds` (users playlists kinds). Получение списка идентификаторов (kind) плейлистов пользователя.',
        "schema": {'type': 'object', 'properties': {'user_id': {'type': 'string'}}, 'additionalProperties': True},
    },
    {
        "method": "users_playlists_list",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_playlists_list` (users playlists list). Получение списка плейлистов пользователя.',
        "schema": {'type': 'object', 'properties': {'user_id': {'type': 'string'}}, 'additionalProperties': True},
    },
    {
        "method": "users_playlists_name",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_playlists_name` (users playlists name). Изменение названия плейлиста.',
        "schema": {'type': 'object', 'properties': {'kind': {'description': 'Parameter `kind` (passed to Yandex Music API).'}, 'name': {'description': 'Parameter `name` (passed to Yandex Music API).'}, 'user_id': {'type': 'string'}}, 'required': ['kind', 'name'], 'additionalProperties': True},
    },
    {
        "method": "users_playlists_recommendations",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_playlists_recommendations` (users playlists recommendations). Получение рекомендаций для плейлиста.',
        "schema": {'type': 'object', 'properties': {'kind': {'description': 'Parameter `kind` (passed to Yandex Music API).'}, 'user_id': {'type': 'string'}}, 'required': ['kind'], 'additionalProperties': True},
    },
    {
        "method": "users_playlists_trailer",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_playlists_trailer` (users playlists trailer). Получение трейлера плейлиста.',
        "schema": {'type': 'object', 'properties': {'kind': {'description': 'Parameter `kind` (passed to Yandex Music API).'}, 'user_id': {'type': 'string'}}, 'required': ['kind'], 'additionalProperties': True},
    },
    {
        "method": "users_playlists_visibility",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_playlists_visibility` (users playlists visibility). Изменение видимости плейлиста.',
        "schema": {'type': 'object', 'properties': {'kind': {'description': 'Parameter `kind` (passed to Yandex Music API).'}, 'visibility': {'description': 'Parameter `visibility` (passed to Yandex Music API).'}, 'user_id': {'type': 'string'}}, 'required': ['kind', 'visibility'], 'additionalProperties': True},
    },
    {
        "method": "users_presaves",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_presaves` (users presaves). Получение списка предсохранённых альбомов.',
        "schema": {'type': 'object', 'properties': {'include_released': {'type': 'boolean', 'default': False}, 'include_upcoming': {'type': 'boolean', 'default': True}, 'user_id': {'type': 'string'}}, 'additionalProperties': True},
    },
    {
        "method": "users_presaves_add",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_presaves_add` (users presaves add). Предсохранение альбома.',
        "schema": {'type': 'object', 'properties': {'album_id': {'type': 'string'}, 'like_after_release': {'type': 'boolean', 'default': True}, 'user_id': {'type': 'string'}}, 'required': ['album_id'], 'additionalProperties': True},
    },
    {
        "method": "users_presaves_remove",
        "auth": True,
        "write": True,
        "description": 'Yandex Music API `users_presaves_remove` (users presaves remove). Удаление предсохранения альбома.',
        "schema": {'type': 'object', 'properties': {'album_id': {'type': 'string'}, 'user_id': {'type': 'string'}}, 'required': ['album_id'], 'additionalProperties': True},
    },
    {
        "method": "users_settings",
        "auth": True,
        "write": False,
        "description": 'Yandex Music API `users_settings` (users settings). Получение настроек пользователя.',
        "schema": {'type': 'object', 'properties': {'user_id': {'type': 'string'}}, 'additionalProperties': True},
    },
)

MUSIC_TOOL_COUNT = 141
