from __future__ import annotations

import re

_TOKEN_RE = re.compile(r"[a-z0-9а-яё]+", re.IGNORECASE)

# Tool discovery queries are normally generated by the agent in English.  This
# compact lexicon keeps direct Russian queries useful too, without adding a
# translation service to the hot path.
RU_TOOL_TERMS: dict[str, tuple[str, ...]] = {
    "яндекс": ("yandex",),
    "музыка": ("music",),
    "музыке": ("music",),
    "трек": ("track",),
    "треки": ("tracks",),
    "треков": ("tracks",),
    "песни": ("tracks",),
    "любимые": ("liked", "favorites"),
    "любимых": ("liked", "favorites"),
    "избранное": ("favorites", "liked"),
    "избранные": ("favorites", "liked"),
    "плейлист": ("playlist",),
    "плейлисты": ("playlists", "list", "user"),
    "плейлистов": ("playlists", "list", "user"),
    "покажи": ("list",),
    "показать": ("list",),
    "список": ("list",),
    "списоки": ("list",),
    "найди": ("find", "search"),
    "найти": ("find", "search"),
    "поиск": ("search",),
    "файл": ("file",),
    "файлы": ("files",),
    "файлов": ("files",),
    "маске": ("glob", "pattern"),
    "маска": ("glob", "pattern"),
    "шаблону": ("glob", "pattern"),
    "рабочей": ("workspace",),
    "папке": ("workspace", "folder"),
    "календарь": ("calendar",),
    "календаре": ("calendar",),
    "календаря": ("calendar",),
    "события": ("events",),
    "событие": ("event",),
    "создай": ("create",),
    "добавь": ("create", "add"),
    "сегодня": ("today",),
    "свободное": ("free", "availability"),
    "время": ("time",),
    "почта": ("gmail", "email"),
    "письма": ("messages", "email"),
    "письмо": ("message", "email"),
    "непрочитанные": ("unread",),
    "отправь": ("send",),
    "скачай": ("download",),
    "скачать": ("download",),
    "диск": ("drive",),
    "таблица": ("spreadsheet", "sheets"),
    "таблицы": ("spreadsheet", "sheets"),
    "ячейки": ("cells", "values"),
    "карте": ("maps",),
    "карты": ("maps",),
    "маршрут": ("route", "directions"),
    "рядом": ("nearby",),
}


def raw_tokens(text: str) -> list[str]:
    return [token.lower().replace("ё", "е") for token in _TOKEN_RE.findall(text)]


def normalized_query_tokens(text: str) -> list[str]:
    result: list[str] = []
    seen: set[str] = set()
    for token in raw_tokens(text):
        mapped = RU_TOOL_TERMS.get(token, (token,))
        for value in mapped:
            if value not in seen:
                seen.add(value)
                result.append(value)
    token_set = set(result)
    implied: list[str] = []
    if "unlike" in token_set:
        implied.extend(value for value in ("remove", "like") if value not in token_set)
    if {"user", "playlists"}.issubset(token_set) and "list" not in token_set:
        implied.append("list")
    if {"find", "files", "pattern"}.issubset(token_set) and "glob" not in token_set:
        implied.append("glob")
    playlist_tokens = {"playlist", "playlists"}
    playlist_actions = {
        "add",
        "create",
        "delete",
        "insert",
        "remove",
        "rename",
        "search",
        "update",
    }
    if token_set & playlist_tokens and not token_set & playlist_actions:
        if "list" not in token_set:
            implied.append("list")
        if "user" not in token_set:
            implied.append("user")
    result.extend(implied)
    return result


def normalize_tool_query(text: str) -> str:
    return " ".join(normalized_query_tokens(text))


def infer_query_tags(text: str) -> tuple[str, ...]:
    tokens = set(normalized_query_tokens(text))
    profiles: tuple[tuple[frozenset[str], tuple[str, ...]], ...] = (
        (frozenset({"yandex", "music"}), ("yandex", "music")),
        # Yandex Music is the bot's only registered music provider, so terse
        # agent queries such as "music playlist" can be routed safely.
        (frozenset({"music"}), ("yandex", "music")),
        (frozenset({"gmail"}), ("google", "gmail")),
        (frozenset({"calendar"}), ("google", "calendar")),
        (frozenset({"tasks"}), ("google", "tasks")),
        (frozenset({"drive"}), ("google", "drive")),
        (frozenset({"sheets"}), ("google", "sheets")),
        (frozenset({"spreadsheet"}), ("google", "sheets")),
        (frozenset({"maps"}), ("google", "maps")),
        (frozenset({"workspace"}), ("workspace", "filesystem")),
    )
    for required, tags in profiles:
        if required.issubset(tokens):
            return tags
    return ()
